package it.sinergis.sunshine.suggestion.map4datapojo;

// Generated 10-lug-2015 17.11.03 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Buildingmanager generated by hbm2java
 */
@Entity
@Table(name = "buildingmanager", schema = "suggestion", uniqueConstraints = @UniqueConstraint(columnNames = {
		"buildingid", "pilot", "email" }))
public class Buildingmanager implements java.io.Serializable {
	
	private int id;
	private Long buildingid;
	private String pilot;
	private String email;
	private String name;
	private String description;
	private int climaticzoneid;
	
	public Buildingmanager() {
	}
	
	public Buildingmanager(int id) {
		this.id = id;
	}
	
	public Buildingmanager(int id, Long buildingid, String pilot, String email, String name, String description,
			int climaticzoneid) {
		this.id = id;
		this.buildingid = buildingid;
		this.pilot = pilot;
		this.email = email;
		this.name = name;
		this.description = description;
		this.climaticzoneid = climaticzoneid;
	}
	
	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}
	
	public void setId(int id) {
		this.id = id;
	}
	
	@Column(name = "buildingid")
	public Long getBuildingid() {
		return this.buildingid;
	}
	
	public void setBuildingid(Long buildingid) {
		this.buildingid = buildingid;
	}
	
	@Column(name = "pilot")
	public String getPilot() {
		return this.pilot;
	}
	
	public void setPilot(String pilot) {
		this.pilot = pilot;
	}
	
	@Column(name = "email")
	public String getEmail() {
		return this.email;
	}
	
	public void setEmail(String email) {
		this.email = email;
	}
	
	@Column(name = "name")
	public String getName() {
		return this.name;
	}
	
	public void setName(String name) {
		this.name = name;
	}
	
	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}
	
	public void setDescription(String description) {
		this.description = description;
	}
	
	@Column(name = "climaticzoneid")
	public int getClimaticzoneid() {
		return climaticzoneid;
	}
	
	public void setClimaticzoneid(int climaticzoneid) {
		this.climaticzoneid = climaticzoneid;
	}
	
}
