package it.sinergis.sunshine.suggestion.map4datapojo;

// Generated 2-lug-2015 10.01.53 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.postgis.Geometry;

/**
 * Building generated by hbm2java
 */
@Entity
@Table(name = "building"/* , schema = "ferrara" */)
public class BuildingMap4 implements Serializable {
	
	private int gid;
	
	//private Geometry geom;
	//	private String classid;
	private String name;
	//	private String nature;
	private Integer begin;
	private Integer end;
	//	private String refurbishm;
	private Double heightVal;
	//	private String heightSta;
	//	private String heightRef;
	private Double elevVal;
	//	private String elevRef;
	//	private Integer elevDat;
	private Double aveFloorH;
	private Integer floors;
	private Integer bdgUnits;
	//	private String occLevel;
	private Double heatVol;
	private Double perimeter;
	private Double perCommon;
	
	//	private String typology;
	//	private String assesType;
	private String tempUri;
	private Double tempAvg;
	
	private String irradUri;
	private Double irradHor;
	private Double irradN;
	private Double irradS;
	private Double irradE;
	private Double irradW;
	private Double UWall;
	private Double URoof;
	private Double UFloor;
	private Double UWin;
	private Double deltaU;
	private Integer PWin;
	
	//	private String matWall;
	private Double denWall;
	private Double spHeatWall;
	private Double thermCondWall;
	private Long foiid;
	
	private String tempOutputUri;
	private String onofOutputUri;
	private Double averageOccupants;
	private Double heatFlowOccupants;
	
	//	private String matRoof;
	//	private String matFloor;
	
	public BuildingMap4() {
	}
	
	public BuildingMap4(int gid, String assesType) {
		this.gid = gid;
		//		this.assesType = assesType;
	}
	
	public BuildingMap4(int gid, Geometry geom, String classid, String name, String nature, Integer begin, Integer end,
			String refurbishm, Double heightVal, String heightSta, String heightRef, Double elevVal, String elevRef,
			Integer elevDat, Double aveFloorH, Integer floors, Integer bdgUnits, String occLevel, Double heatVol,
			Double perimeter, Double perCommon, String typology, String assesType, String tempUri, Double tempAvg,
			String irradUri, Double irradHor, Double irradN, Double irradS, Double irradE, Double irradW, Double UWall,
			Double URoof, Double UFloor, Double UWin, Double deltaU, Integer PWin, String matWall, Double denWall,
			Double spHeatWall, Double thermCondWall, String matRoof, String matFloor, Long foiid, String tempOutputUri,
			String onofOutputUri, Double averageOccupants, Double heatFlowOccupants) {
		this.gid = gid;
		//		this.geom = geom;
		//		this.classid = classid;
		this.name = name;
		//		this.nature = nature;
		this.begin = begin;
		this.end = end;
		//		this.refurbishm = refurbishm;
		this.heightVal = heightVal;
		//		this.heightSta = heightSta;
		//		this.heightRef = heightRef;
		this.elevVal = elevVal;
		//		this.elevRef = elevRef;
		//		this.elevDat = elevDat;
		this.aveFloorH = aveFloorH;
		this.floors = floors;
		this.bdgUnits = bdgUnits;
		//		this.occLevel = occLevel;
		this.heatVol = heatVol;
		this.perimeter = perimeter;
		this.perCommon = perCommon;
		//		this.typology = typology;
		//		this.assesType = assesType;
		this.tempUri = tempUri;
		this.tempAvg = tempAvg;
		this.irradUri = irradUri;
		this.irradHor = irradHor;
		this.irradN = irradN;
		this.irradS = irradS;
		this.irradE = irradE;
		this.irradW = irradW;
		this.UWall = UWall;
		this.URoof = URoof;
		this.UFloor = UFloor;
		this.UWin = UWin;
		this.deltaU = deltaU;
		this.PWin = PWin;
		//		this.matWall = matWall;
		this.denWall = denWall;
		this.spHeatWall = spHeatWall;
		this.thermCondWall = thermCondWall;
		this.foiid = foiid;
		this.tempOutputUri = tempOutputUri;
		this.onofOutputUri = onofOutputUri;
		this.averageOccupants = averageOccupants;
		this.heatFlowOccupants = heatFlowOccupants;
		//		this.matRoof = matRoof;
		//		this.matFloor = matFloor;
	}
	
	@Id
	@Column(name = "gid", unique = true, nullable = false)
	public int getGid() {
		return this.gid;
	}
	
	public void setGid(int gid) {
		this.gid = gid;
	}
	
	//	@Column(name = "geom")
	//	public Geometry getGeom() {
	//		return this.geom;
	//	}
	//	
	//	public void setGeom(Geometry geom) {
	//		this.geom = geom;
	//	}
	//	
	//	@Column(name = "classid", length = 70)
	//	public String getClassid() {
	//		return this.classid;
	//	}
	//	
	//	public void setClassid(String classid) {
	//		this.classid = classid;
	//	}
	
	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}
	
	public void setName(String name) {
		this.name = name;
	}
	
	//	@Column(name = "nature")
	//	public String getNature() {
	//		return this.nature;
	//	}
	//	
	//	public void setNature(String nature) {
	//		this.nature = nature;
	//	}
	
	@Column(name = "begin")
	public Integer getBegin() {
		return this.begin;
	}
	
	public void setBegin(Integer begin) {
		this.begin = begin;
	}
	
	@Column(name = "end")
	public Integer getEnd() {
		return this.end;
	}
	
	public void setEnd(Integer end) {
		this.end = end;
	}
	
	//	@Column(name = "refurbishm")
	//	public String getRefurbishm() {
	//		return this.refurbishm;
	//	}
	//	
	//	public void setRefurbishm(String refurbishm) {
	//		this.refurbishm = refurbishm;
	//	}
	
	@Column(name = "height_val", precision = 17, scale = 17)
	public Double getHeightVal() {
		return this.heightVal;
	}
	
	public void setHeightVal(Double heightVal) {
		this.heightVal = heightVal;
	}
	
	//	@Column(name = "height_sta")
	//	public String getHeightSta() {
	//		return this.heightSta;
	//	}
	//	
	//	public void setHeightSta(String heightSta) {
	//		this.heightSta = heightSta;
	//	}
	//	
	//	@Column(name = "height_ref")
	//	public String getHeightRef() {
	//		return this.heightRef;
	//	}
	//	
	//	public void setHeightRef(String heightRef) {
	//		this.heightRef = heightRef;
	//	}
	
	@Column(name = "elev_val", precision = 17, scale = 17)
	public Double getElevVal() {
		return this.elevVal;
	}
	
	public void setElevVal(Double elevVal) {
		this.elevVal = elevVal;
	}
	
	//	@Column(name = "elev_ref")
	//	public String getElevRef() {
	//		return this.elevRef;
	//	}
	//	
	//	public void setElevRef(String elevRef) {
	//		this.elevRef = elevRef;
	//	}
	//	
	//	@Column(name = "elev_dat")
	//	public Integer getElevDat() {
	//		return this.elevDat;
	//	}
	//	
	//	public void setElevDat(Integer elevDat) {
	//		this.elevDat = elevDat;
	//	}
	
	@Column(name = "ave_floor_h", precision = 17, scale = 17)
	public Double getAveFloorH() {
		return this.aveFloorH;
	}
	
	public void setAveFloorH(Double aveFloorH) {
		this.aveFloorH = aveFloorH;
	}
	
	@Column(name = "floors")
	public Integer getFloors() {
		return this.floors;
	}
	
	public void setFloors(Integer floors) {
		this.floors = floors;
	}
	
	@Column(name = "bdg_units")
	public Integer getBdgUnits() {
		return this.bdgUnits;
	}
	
	public void setBdgUnits(Integer bdgUnits) {
		this.bdgUnits = bdgUnits;
	}
	
	//	@Column(name = "occ_level")
	//	public String getOccLevel() {
	//		return this.occLevel;
	//	}
	//	
	//	public void setOccLevel(String occLevel) {
	//		this.occLevel = occLevel;
	//	}
	
	@Column(name = "heat_vol", precision = 17, scale = 17)
	public Double getHeatVol() {
		return this.heatVol;
	}
	
	public void setHeatVol(Double heatVol) {
		this.heatVol = heatVol;
	}
	
	@Column(name = "perimeter", precision = 17, scale = 17)
	public Double getPerimeter() {
		return this.perimeter;
	}
	
	public void setPerimeter(Double perimeter) {
		this.perimeter = perimeter;
	}
	
	@Column(name = "per_common", precision = 17, scale = 17)
	public Double getPerCommon() {
		return this.perCommon;
	}
	
	public void setPerCommon(Double perCommon) {
		this.perCommon = perCommon;
	}
	
	//	@Column(name = "typology")
	//	public String getTypology() {
	//		return this.typology;
	//	}
	//	
	//	public void setTypology(String typology) {
	//		this.typology = typology;
	//	}
	//	
	//	@Column(name = "asses_type", nullable = false)
	//	public String getAssesType() {
	//		return this.assesType;
	//	}
	//	
	//	public void setAssesType(String assesType) {
	//		this.assesType = assesType;
	//	}
	
	@Column(name = "temp_uri")
	public String getTempUri() {
		return this.tempUri;
	}
	
	public void setTempUri(String tempUri) {
		this.tempUri = tempUri;
	}
	
	@Column(name = "temp_avg", precision = 17, scale = 17)
	public Double getTempAvg() {
		return this.tempAvg;
	}
	
	public void setTempAvg(Double tempAvg) {
		this.tempAvg = tempAvg;
	}
	
	@Column(name = "irrad_uri")
	public String getIrradUri() {
		return this.irradUri;
	}
	
	public void setIrradUri(String irradUri) {
		this.irradUri = irradUri;
	}
	
	@Column(name = "irrad_hor", precision = 17, scale = 17)
	public Double getIrradHor() {
		return this.irradHor;
	}
	
	public void setIrradHor(Double irradHor) {
		this.irradHor = irradHor;
	}
	
	@Column(name = "irrad_n", precision = 17, scale = 17)
	public Double getIrradN() {
		return this.irradN;
	}
	
	public void setIrradN(Double irradN) {
		this.irradN = irradN;
	}
	
	@Column(name = "irrad_s", precision = 17, scale = 17)
	public Double getIrradS() {
		return this.irradS;
	}
	
	public void setIrradS(Double irradS) {
		this.irradS = irradS;
	}
	
	@Column(name = "irrad_e", precision = 17, scale = 17)
	public Double getIrradE() {
		return this.irradE;
	}
	
	public void setIrradE(Double irradE) {
		this.irradE = irradE;
	}
	
	@Column(name = "irrad_w", precision = 17, scale = 17)
	public Double getIrradW() {
		return this.irradW;
	}
	
	public void setIrradW(Double irradW) {
		this.irradW = irradW;
	}
	
	@Column(name = "u_wall", precision = 17, scale = 17)
	public Double getUWall() {
		return this.UWall;
	}
	
	public void setUWall(Double UWall) {
		this.UWall = UWall;
	}
	
	@Column(name = "u_roof", precision = 17, scale = 17)
	public Double getURoof() {
		return this.URoof;
	}
	
	public void setURoof(Double URoof) {
		this.URoof = URoof;
	}
	
	@Column(name = "u_floor", precision = 17, scale = 17)
	public Double getUFloor() {
		return this.UFloor;
	}
	
	public void setUFloor(Double UFloor) {
		this.UFloor = UFloor;
	}
	
	@Column(name = "u_win", precision = 17, scale = 17)
	public Double getUWin() {
		return this.UWin;
	}
	
	public void setUWin(Double UWin) {
		this.UWin = UWin;
	}
	
	@Column(name = "delta_u", precision = 17, scale = 17)
	public Double getDeltaU() {
		return this.deltaU;
	}
	
	public void setDeltaU(Double deltaU) {
		this.deltaU = deltaU;
	}
	
	@Column(name = "p_win")
	public Integer getPWin() {
		return this.PWin;
	}
	
	public void setPWin(Integer PWin) {
		this.PWin = PWin;
	}
	
	//	@Column(name = "mat_wall", length = 40)
	//	public String getMatWall() {
	//		return this.matWall;
	//	}
	//	
	//	public void setMatWall(String matWall) {
	//		this.matWall = matWall;
	//	}
	
	@Column(name = "den_wall", precision = 17, scale = 17)
	public Double getDenWall() {
		return this.denWall;
	}
	
	public void setDenWall(Double denWall) {
		this.denWall = denWall;
	}
	
	@Column(name = "sp_heat_wall", precision = 17, scale = 17)
	public Double getSpHeatWall() {
		return this.spHeatWall;
	}
	
	public void setSpHeatWall(Double spHeatWall) {
		this.spHeatWall = spHeatWall;
	}
	
	@Column(name = "therm_cond_wall", precision = 17, scale = 17)
	public Double getThermCondWall() {
		return this.thermCondWall;
	}
	
	public void setThermCondWall(Double thermCondWall) {
		this.thermCondWall = thermCondWall;
	}
	
	@Column(name = "foiid")
	public Long getFoiid() {
		return foiid;
	}
	
	public void setFoiid(Long foiid) {
		this.foiid = foiid;
	}
	
	@Column(name = "temp_output_uri")
	public String getTempOutputUri() {
		return tempOutputUri;
	}
	
	public void setTempOutputUri(String tempOutputUri) {
		this.tempOutputUri = tempOutputUri;
	}
	
	@Column(name = "onof_output_uri")
	public String getOnofOutputUri() {
		return onofOutputUri;
	}
	
	public void setOnofOutputUri(String onofOutputUri) {
		this.onofOutputUri = onofOutputUri;
	}
	
	@Column(name = "average_occupants")
	public Double getAverageOccupants() {
		return averageOccupants;
	}
	
	public void setAverageOccupants(Double averageOccupants) {
		this.averageOccupants = averageOccupants;
	}
	
	@Column(name = "heat_flow_occupants")
	public Double getHeatFlowOccupants() {
		return heatFlowOccupants;
	}
	
	public void setHeatFlowOccupants(Double heatFlowOccupants) {
		this.heatFlowOccupants = heatFlowOccupants;
	}
	
	//	@Column(name = "mat_roof", length = 50)
	//	public String getMatRoof() {
	//		return this.matRoof;
	//	}
	//	
	//	public void setMatRoof(String matRoof) {
	//		this.matRoof = matRoof;
	//	}
	//	
	//	@Column(name = "mat_floor", length = 50)
	//	public String getMatFloor() {
	//		return this.matFloor;
	//	}
	//	
	//	public void setMatFloor(String matFloor) {
	//		this.matFloor = matFloor;
	//	}
	
}
