package it.sinergis.sunshine.suggestion.map4datapojo;

// Generated 2-nov-2015 11.05.10 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Calendarshelter generated by hbm2java
 */
@Entity
@Table(name = "calendarshelter", schema = "suggestion")
public class Calendarshelter implements java.io.Serializable {
	
	private long calendarshelterid;
	private Integer thresholdwarm;
	private Integer thresholdcold;
	private Date day;
	private Integer shelterid;
	
	public Calendarshelter() {
	}
	
	public Calendarshelter(long calendarshelterid) {
		this.calendarshelterid = calendarshelterid;
	}
	
	public Calendarshelter(long calendarshelterid, Integer thresholdwarm, Integer thresholdcold, Date day,
			Integer shelterid) {
		this.calendarshelterid = calendarshelterid;
		this.thresholdwarm = thresholdwarm;
		this.thresholdcold = thresholdcold;
		this.day = day;
		this.shelterid = shelterid;
	}
	
	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "devices_seq_gen")
	@SequenceGenerator(name = "devices_seq_gen", sequenceName = "suggestion.calendarshelter_sequence", allocationSize = 1)
	@Column(name = "calendarshelterid", unique = true, nullable = false)
	public long getCalendarshelterid() {
		return this.calendarshelterid;
	}
	
	public void setCalendarshelterid(long calendarshelterid) {
		this.calendarshelterid = calendarshelterid;
	}
	
	@Column(name = "thresholdwarm")
	public Integer getThresholdwarm() {
		return this.thresholdwarm;
	}
	
	public void setThresholdwarm(Integer thresholdwarm) {
		this.thresholdwarm = thresholdwarm;
	}
	
	@Column(name = "thresholdcold")
	public Integer getThresholdcold() {
		return this.thresholdcold;
	}
	
	public void setThresholdcold(Integer thresholdcold) {
		this.thresholdcold = thresholdcold;
	}
	
	@Temporal(TemporalType.DATE)
	@Column(name = "day", length = 13)
	public Date getDay() {
		return this.day;
	}
	
	public void setDay(Date day) {
		this.day = day;
	}
	
	@Column(name = "shelterid")
	public Integer getShelterid() {
		return this.shelterid;
	}
	
	public void setShelterid(Integer shelterid) {
		this.shelterid = shelterid;
	}
	
}
