package it.sinergis.sunshine.suggestion.map4datapojo;

// Generated 30-lug-2015 10.15.49 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ClimaticZones generated by hbm2java
 */
@Entity
@Table(name = "climatic_zones", schema = "configurations")
public class ClimaticZones implements java.io.Serializable {
	
	private int id;
	private String name;
	private String country;
	private Integer irradiation;
	private Integer heatingDays;
	private Double theta;
	private Integer dd;
	private Integer heatingStart;
	private Integer heatingEnd;
	private Double thresholdTmin;
	private Double thresholdTmed;
	private Double thresholdTmax;
	
	public ClimaticZones() {
	}
	
	public ClimaticZones(int id) {
		this.id = id;
	}
	
	public ClimaticZones(int id, String name, String country, Integer irradiation, Integer heatingDays, Double theta,
			Integer dd, Integer heatingStart, Integer heatingEnd, Double thresholdTmin, Double thresholdTmed,
			Double thresholdTmax) {
		this.id = id;
		this.name = name;
		this.country = country;
		this.irradiation = irradiation;
		this.heatingDays = heatingDays;
		this.theta = theta;
		this.dd = dd;
		this.heatingStart = heatingStart;
		this.heatingEnd = heatingEnd;
		this.thresholdTmin = thresholdTmin;
		this.thresholdTmed = thresholdTmed;
		this.thresholdTmax = thresholdTmax;
	}
	
	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}
	
	public void setId(int id) {
		this.id = id;
	}
	
	@Column(name = "name")
	public String getName() {
		return this.name;
	}
	
	public void setName(String name) {
		this.name = name;
	}
	
	@Column(name = "country")
	public String getCountry() {
		return this.country;
	}
	
	public void setCountry(String country) {
		this.country = country;
	}
	
	@Column(name = "irradiation")
	public Integer getIrradiation() {
		return this.irradiation;
	}
	
	public void setIrradiation(Integer irradiation) {
		this.irradiation = irradiation;
	}
	
	@Column(name = "heating_days")
	public Integer getHeatingDays() {
		return this.heatingDays;
	}
	
	public void setHeatingDays(Integer heatingDays) {
		this.heatingDays = heatingDays;
	}
	
	@Column(name = "theta", precision = 17, scale = 17)
	public Double getTheta() {
		return this.theta;
	}
	
	public void setTheta(Double theta) {
		this.theta = theta;
	}
	
	@Column(name = "dd")
	public Integer getDd() {
		return this.dd;
	}
	
	public void setDd(Integer dd) {
		this.dd = dd;
	}
	
	@Column(name = "heating_start")
	public Integer getHeatingStart() {
		return this.heatingStart;
	}
	
	public void setHeatingStart(Integer heatingStart) {
		this.heatingStart = heatingStart;
	}
	
	@Column(name = "heating_end")
	public Integer getHeatingEnd() {
		return this.heatingEnd;
	}
	
	public void setHeatingEnd(Integer heatingEnd) {
		this.heatingEnd = heatingEnd;
	}
	
	@Column(name = "thresholdtmin", precision = 17, scale = 17)
	public Double getThresholdTmin() {
		return this.thresholdTmin;
	}
	
	public void setThresholdTmin(Double thresholdTmin) {
		this.thresholdTmin = thresholdTmin;
	}
	
	@Column(name = "thresholdtmed", precision = 17, scale = 17)
	public Double getThresholdTmed() {
		return this.thresholdTmed;
	}
	
	public void setThresholdTmed(Double thresholdTmed) {
		this.thresholdTmed = thresholdTmed;
	}
	
	@Column(name = "thresholdtmax", precision = 17, scale = 17)
	public Double getThresholdTmax() {
		return this.thresholdTmax;
	}
	
	public void setThresholdTmax(Double thresholdTmax) {
		this.thresholdTmax = thresholdTmax;
	}
	
}
