package it.sinergis.sunshine.suggestion.map4datapojo;

// Generated 9-nov-2015 14.17.51 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Energyamount generated by hbm2java
 */
@Entity
@Table(name = "energyamount")
public class Energyamount implements java.io.Serializable {
	
	private int id;
	private Integer idThermalzone;
	private String ESource;
	private String EType;
	private String EUse;
	private Double EAmount;
	private String EUri;
	private String EUom;
	private Double ECost;
	private String ECur;
	private Integer EYear;
	private Integer EPerc;
	
	public Energyamount() {
	}
	
	public Energyamount(int id, String EType) {
		this.id = id;
		this.EType = EType;
	}
	
	public Energyamount(int id, Integer idThermalzone, String ESource, String EType, String EUse, Double EAmount,
			String EUri, String EUom, Double ECost, String ECur, Integer EYear, Integer EPerc) {
		this.id = id;
		this.idThermalzone = idThermalzone;
		this.ESource = ESource;
		this.EType = EType;
		this.EUse = EUse;
		this.EAmount = EAmount;
		this.EUri = EUri;
		this.EUom = EUom;
		this.ECost = ECost;
		this.ECur = ECur;
		this.EYear = EYear;
		this.EPerc = EPerc;
	}
	
	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}
	
	public void setId(int id) {
		this.id = id;
	}
	
	@Column(name = "id_thermalzone")
	public Integer getIdThermalzone() {
		return this.idThermalzone;
	}
	
	public void setIdThermalzone(Integer idThermalzone) {
		this.idThermalzone = idThermalzone;
	}
	
	@Column(name = "e_source")
	public String getESource() {
		return this.ESource;
	}
	
	public void setESource(String ESource) {
		this.ESource = ESource;
	}
	
	@Column(name = "e_type", nullable = false)
	public String getEType() {
		return this.EType;
	}
	
	public void setEType(String EType) {
		this.EType = EType;
	}
	
	@Column(name = "e_use")
	public String getEUse() {
		return this.EUse;
	}
	
	public void setEUse(String EUse) {
		this.EUse = EUse;
	}
	
	@Column(name = "e_amount", precision = 17, scale = 17)
	public Double getEAmount() {
		return this.EAmount;
	}
	
	public void setEAmount(Double EAmount) {
		this.EAmount = EAmount;
	}
	
	@Column(name = "e_uri")
	public String getEUri() {
		return this.EUri;
	}
	
	public void setEUri(String EUri) {
		this.EUri = EUri;
	}
	
	@Column(name = "e_uom", length = 50)
	public String getEUom() {
		return this.EUom;
	}
	
	public void setEUom(String EUom) {
		this.EUom = EUom;
	}
	
	@Column(name = "e_cost", precision = 17, scale = 17)
	public Double getECost() {
		return this.ECost;
	}
	
	public void setECost(Double ECost) {
		this.ECost = ECost;
	}
	
	@Column(name = "e_cur", length = 3)
	public String getECur() {
		return this.ECur;
	}
	
	public void setECur(String ECur) {
		this.ECur = ECur;
	}
	
	@Column(name = "e_year")
	public Integer getEYear() {
		return this.EYear;
	}
	
	public void setEYear(Integer EYear) {
		this.EYear = EYear;
	}
	
	@Column(name = "e_perc")
	public Integer getEPerc() {
		return this.EPerc;
	}
	
	public void setEPerc(Integer EPerc) {
		this.EPerc = EPerc;
	}
	
}
