package it.sinergis.sunshine.suggestion.map4datapojo;

// Generated 28-lug-2015 9.31.28 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Heatingsystem generated by hbm2java
 */
@Entity
@Table(name = "heatingsystem")
public class Heatingsystem implements java.io.Serializable {
	
	private int id;
	private Integer idThermalzone;
	private String heatSyst;
	private Double heatEff;
	private String heatCtr; //{fixedpoint,climatic,teleheating} sul db (0 fixed point ;  1 climatic/teleheating)
	
	public Heatingsystem() {
	}
	
	public Heatingsystem(int id, String heatSyst) {
		this.id = id;
		this.heatSyst = heatSyst;
	}
	
	public Heatingsystem(int id, Integer idThermalzone, String heatSyst, Double heatEff, String heatCtr) {
		this.id = id;
		this.idThermalzone = idThermalzone;
		this.heatSyst = heatSyst;
		this.heatEff = heatEff;
		this.heatCtr = heatCtr;
	}
	
	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}
	
	public void setId(int id) {
		this.id = id;
	}
	
	@Column(name = "id_thermalzone")
	public Integer getIdThermalzone() {
		return this.idThermalzone;
	}
	
	public void setIdThermalzone(Integer idThermalzone) {
		this.idThermalzone = idThermalzone;
	}
	
	@Column(name = "heat_syst", nullable = false)
	public String getHeatSyst() {
		return this.heatSyst;
	}
	
	public void setHeatSyst(String heatSyst) {
		this.heatSyst = heatSyst;
	}
	
	@Column(name = "heat_eff", precision = 17, scale = 17)
	public Double getHeatEff() {
		return this.heatEff;
	}
	
	public void setHeatEff(Double heatEff) {
		this.heatEff = heatEff;
	}
	
	@Column(name = "heat_ctr")
	public String getHeatCtr() {
		return this.heatCtr;
	}
	
	public void setHeatCtr(String heatCtr) {
		this.heatCtr = heatCtr;
	}
	
}
