package it.sinergis.sunshine.suggestion.map4datapojo;

// Generated 3-lug-2015 12.21.50 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Officialarea generated by hbm2java
 */
@Entity
@Table(name = "officialarea", /* schema = "ferrara", */uniqueConstraints = @UniqueConstraint(columnNames = {
		"id_building", "area_ref" }))
public class Officialarea implements Serializable {
	
	private int id;
	private Integer idBuilding;
	private Double clgeValue;
	private String areaRef;
	
	public Officialarea() {
	}
	
	public Officialarea(int id) {
		this.id = id;
	}
	
	public Officialarea(int id, Integer idBuilding, Double clgeValue, String areaRef) {
		this.id = id;
		this.idBuilding = idBuilding;
		this.clgeValue = clgeValue;
		this.areaRef = areaRef;
	}
	
	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}
	
	public void setId(int id) {
		this.id = id;
	}
	
	@Column(name = "id_building")
	public Integer getIdBuilding() {
		return this.idBuilding;
	}
	
	public void setIdBuilding(Integer idBuilding) {
		this.idBuilding = idBuilding;
	}
	
	@Column(name = "clge_value", precision = 17, scale = 17)
	public Double getClgeValue() {
		return this.clgeValue;
	}
	
	public void setClgeValue(Double clgeValue) {
		this.clgeValue = clgeValue;
	}
	
	@Column(name = "area_ref")
	public String getAreaRef() {
		return this.areaRef;
	}
	
	public void setAreaRef(String areaRef) {
		this.areaRef = areaRef;
	}
	
}
