package it.sinergis.sunshine.suggestion.map4datapojo;

// Generated 27-ago-2015 11.36.15 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Shelter generated by hbm2java
 */
@Entity
@Table(name = "shelter", schema = "suggestion")
public class ShelterMap4 implements java.io.Serializable {
	
	private int id;
	private Double caloreinterno;
	private Double uparete;
	private Double utetto;
	private Double upavimento;
	private Double aparete;
	private Double areatetto;
	private Double volume;
	private Double capacitainterna;
	private Double capacitaesterna;
	private String pilot;
	private String uriirra;
	private String uritemp;
	private String uriwind;
	private Integer threshold;
	private String description;
	private String uriofferingcountheat;
	private String uriofferingcountcold;
	private String uriprocedure;
	private String urifoi;
	
	public ShelterMap4() {
	}
	
	public ShelterMap4(int id) {
		this.id = id;
	}
	
	public ShelterMap4(int id, Double caloreinterno, Double uparete, Double utetto, Double upavimento, Double aparete,
			Double areatetto, Double volume, Double capacitainterna, Double capacitaesterna, String pilot,
			String uriirra, String uritemp, String uriwind, Integer threshold, String description,
			String uriofferingcountheat, String uriofferingcountcold, String uriprocedure, String urifoi) {
		this.id = id;
		this.caloreinterno = caloreinterno;
		this.uparete = uparete;
		this.utetto = utetto;
		this.upavimento = upavimento;
		this.aparete = aparete;
		this.areatetto = areatetto;
		this.volume = volume;
		this.capacitainterna = capacitainterna;
		this.capacitaesterna = capacitaesterna;
		this.pilot = pilot;
		this.uriirra = uriirra;
		this.uritemp = uritemp;
		this.uriwind = uriwind;
		this.threshold = threshold;
		this.description = description;
		this.uriofferingcountheat = uriofferingcountheat;
		this.uriofferingcountcold = uriofferingcountcold;
		this.uriprocedure = uriprocedure;
		this.urifoi = urifoi;
	}
	
	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}
	
	public void setId(int id) {
		this.id = id;
	}
	
	@Column(name = "caloreinterno", precision = 17, scale = 17)
	public Double getCaloreinterno() {
		return this.caloreinterno;
	}
	
	public void setCaloreinterno(Double caloreinterno) {
		this.caloreinterno = caloreinterno;
	}
	
	@Column(name = "uparete", precision = 17, scale = 17)
	public Double getUparete() {
		return this.uparete;
	}
	
	public void setUparete(Double uparete) {
		this.uparete = uparete;
	}
	
	@Column(name = "utetto", precision = 17, scale = 17)
	public Double getUtetto() {
		return this.utetto;
	}
	
	public void setUtetto(Double utetto) {
		this.utetto = utetto;
	}
	
	@Column(name = "upavimento", precision = 17, scale = 17)
	public Double getUpavimento() {
		return this.upavimento;
	}
	
	public void setUpavimento(Double upavimento) {
		this.upavimento = upavimento;
	}
	
	@Column(name = "aparete", precision = 17, scale = 17)
	public Double getAparete() {
		return this.aparete;
	}
	
	public void setAparete(Double aparete) {
		this.aparete = aparete;
	}
	
	@Column(name = "areatetto", precision = 17, scale = 17)
	public Double getAreatetto() {
		return this.areatetto;
	}
	
	public void setAreatetto(Double areatetto) {
		this.areatetto = areatetto;
	}
	
	@Column(name = "volume", precision = 17, scale = 17)
	public Double getVolume() {
		return this.volume;
	}
	
	public void setVolume(Double volume) {
		this.volume = volume;
	}
	
	@Column(name = "capacitainterna", precision = 17, scale = 17)
	public Double getCapacitainterna() {
		return this.capacitainterna;
	}
	
	public void setCapacitainterna(Double capacitainterna) {
		this.capacitainterna = capacitainterna;
	}
	
	@Column(name = "capacitaesterna", precision = 17, scale = 17)
	public Double getCapacitaesterna() {
		return this.capacitaesterna;
	}
	
	public void setCapacitaesterna(Double capacitaesterna) {
		this.capacitaesterna = capacitaesterna;
	}
	
	@Column(name = "pilot")
	public String getPilot() {
		return this.pilot;
	}
	
	public void setPilot(String pilot) {
		this.pilot = pilot;
	}
	
	@Column(name = "uriirra")
	public String getUriirra() {
		return this.uriirra;
	}
	
	public void setUriirra(String uriirra) {
		this.uriirra = uriirra;
	}
	
	@Column(name = "uritemp")
	public String getUritemp() {
		return this.uritemp;
	}
	
	public void setUritemp(String uritemp) {
		this.uritemp = uritemp;
	}
	
	@Column(name = "uriwind")
	public String getUriwind() {
		return this.uriwind;
	}
	
	public void setUriwind(String uriwind) {
		this.uriwind = uriwind;
	}
	
	@Column(name = "threshold")
	public Integer getThreshold() {
		return this.threshold;
	}
	
	public void setThreshold(Integer threshold) {
		this.threshold = threshold;
	}
	
	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}
	
	public void setDescription(String description) {
		this.description = description;
	}
	
	@Column(name = "uriofferingcountheat")
	public String getUriofferingcountheat() {
		return this.uriofferingcountheat;
	}
	
	public void setUriofferingcountheat(String uriofferingcountheat) {
		this.uriofferingcountheat = uriofferingcountheat;
	}
	
	@Column(name = "uriofferingcountcold")
	public String getUriofferingcountcold() {
		return this.uriofferingcountcold;
	}
	
	public void setUriofferingcountcold(String uriofferingcountcold) {
		this.uriofferingcountcold = uriofferingcountcold;
	}
	
	@Column(name = "uriprocedure")
	public String getUriprocedure() {
		return this.uriprocedure;
	}
	
	public void setUriprocedure(String uriprocedure) {
		this.uriprocedure = uriprocedure;
	}
	
	@Column(name = "urifoi")
	public String getUrifoi() {
		return this.urifoi;
	}
	
	public void setUrifoi(String urifoi) {
		this.urifoi = urifoi;
	}
	
}
