package it.sinergis.sunshine.suggestion.sospojo;

// Generated 11-nov-2015 15.12.37 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Featureofinterest generated by hbm2java
 */
@Entity
@Table(name = "featureofinterest", schema = "public", uniqueConstraints = { @UniqueConstraint(columnNames = "url"),
		@UniqueConstraint(columnNames = "identifier") })
public class Featureofinterest implements java.io.Serializable {
	
	private long featureofinterestid;
	private char hibernatediscriminator;
	private long featureofinteresttypeid;
	private String identifier;
	private Long codespaceid;
	private String name;
	private String geom;
	private String descriptionxml;
	private String url;
	
	public Featureofinterest() {
	}
	
	public Featureofinterest(long featureofinterestid, char hibernatediscriminator, long featureofinteresttypeid) {
		this.featureofinterestid = featureofinterestid;
		this.hibernatediscriminator = hibernatediscriminator;
		this.featureofinteresttypeid = featureofinteresttypeid;
	}
	
	public Featureofinterest(long featureofinterestid, char hibernatediscriminator, long featureofinteresttypeid,
			String identifier, Long codespaceid, String name, String geom, String descriptionxml, String url) {
		this.featureofinterestid = featureofinterestid;
		this.hibernatediscriminator = hibernatediscriminator;
		this.featureofinteresttypeid = featureofinteresttypeid;
		this.identifier = identifier;
		this.codespaceid = codespaceid;
		this.name = name;
		this.geom = geom;
		this.descriptionxml = descriptionxml;
		this.url = url;
	}
	
	@Id
	@Column(name = "featureofinterestid", unique = true, nullable = false)
	public long getFeatureofinterestid() {
		return this.featureofinterestid;
	}
	
	public void setFeatureofinterestid(long featureofinterestid) {
		this.featureofinterestid = featureofinterestid;
	}
	
	@Column(name = "hibernatediscriminator", nullable = false, length = 1)
	public char getHibernatediscriminator() {
		return this.hibernatediscriminator;
	}
	
	public void setHibernatediscriminator(char hibernatediscriminator) {
		this.hibernatediscriminator = hibernatediscriminator;
	}
	
	@Column(name = "featureofinteresttypeid", nullable = false)
	public long getFeatureofinteresttypeid() {
		return this.featureofinteresttypeid;
	}
	
	public void setFeatureofinteresttypeid(long featureofinteresttypeid) {
		this.featureofinteresttypeid = featureofinteresttypeid;
	}
	
	@Column(name = "identifier", unique = true)
	public String getIdentifier() {
		return this.identifier;
	}
	
	public void setIdentifier(String identifier) {
		this.identifier = identifier;
	}
	
	@Column(name = "codespaceid")
	public Long getCodespaceid() {
		return this.codespaceid;
	}
	
	public void setCodespaceid(Long codespaceid) {
		this.codespaceid = codespaceid;
	}
	
	@Column(name = "name")
	public String getName() {
		return this.name;
	}
	
	public void setName(String name) {
		this.name = name;
	}
	
	@Column(name = "geom")
	public String getGeom() {
		return this.geom;
	}
	
	public void setGeom(String geom) {
		this.geom = geom;
	}
	
	@Column(name = "descriptionxml")
	public String getDescriptionxml() {
		return this.descriptionxml;
	}
	
	public void setDescriptionxml(String descriptionxml) {
		this.descriptionxml = descriptionxml;
	}
	
	@Column(name = "url", unique = true)
	public String getUrl() {
		return this.url;
	}
	
	public void setUrl(String url) {
		this.url = url;
	}
	
}
