package it.sinergis.sunshine.suggestion.sospojo;

// Generated 3-lug-2015 14.52.41 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Numericvalue generated by hbm2java
 */
@Entity
@Table(name = "numericvalue", schema = "public")
public class Numericvalue implements java.io.Serializable {
	
	private long observationid;
	private Double value;
	
	public Numericvalue() {
	}
	
	public Numericvalue(long observationid) {
		this.observationid = observationid;
	}
	
	public Numericvalue(long observationid, Double value) {
		this.observationid = observationid;
		this.value = value;
	}
	
	@Id
	@Column(name = "observationid", unique = true, nullable = false)
	public long getObservationid() {
		return this.observationid;
	}
	
	public void setObservationid(long observationid) {
		this.observationid = observationid;
	}
	
	@Column(name = "value", precision = 17, scale = 17)
	public Double getValue() {
		return this.value;
	}
	
	public void setValue(Double value) {
		this.value = value;
	}
	
}
