package it.sinergis.sunshine.suggestion.sospojo;

// Generated 2-lug-2015 17.16.09 by Hibernate Tools 4.0.0

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Observation generated by hbm2java
 */
@Entity
@Table(name = "observation", schema = "public", uniqueConstraints = {
		@UniqueConstraint(columnNames = { "seriesid", "phenomenontimestart", "phenomenontimeend", "resulttime" }),
		@UniqueConstraint(columnNames = "identifier") })
public class Observation implements java.io.Serializable {
	
	private long observationid;
	private long seriesid;
	private Date phenomenontimestart;
	private Date phenomenontimeend;
	private Date resulttime;
	private String identifier;
	private Long codespaceid;
	private String description;
	private char deleted;
	private Date validtimestart;
	private Date validtimeend;
	private Long unitid;
	private Serializable samplinggeometry;
	
	public Observation() {
	}
	
	public Observation(long observationid, long seriesid, Date phenomenontimestart, Date phenomenontimeend,
			Date resulttime, char deleted) {
		this.observationid = observationid;
		this.seriesid = seriesid;
		this.phenomenontimestart = phenomenontimestart;
		this.phenomenontimeend = phenomenontimeend;
		this.resulttime = resulttime;
		this.deleted = deleted;
	}
	
	public Observation(long observationid, long seriesid, Date phenomenontimestart, Date phenomenontimeend,
			Date resulttime, String identifier, Long codespaceid, String description, char deleted,
			Date validtimestart, Date validtimeend, Long unitid, Serializable samplinggeometry) {
		this.observationid = observationid;
		this.seriesid = seriesid;
		this.phenomenontimestart = phenomenontimestart;
		this.phenomenontimeend = phenomenontimeend;
		this.resulttime = resulttime;
		this.identifier = identifier;
		this.codespaceid = codespaceid;
		this.description = description;
		this.deleted = deleted;
		this.validtimestart = validtimestart;
		this.validtimeend = validtimeend;
		this.unitid = unitid;
		this.samplinggeometry = samplinggeometry;
	}
	
	@Id
	@Column(name = "observationid", unique = true, nullable = false)
	public long getObservationid() {
		return this.observationid;
	}
	
	public void setObservationid(long observationid) {
		this.observationid = observationid;
	}
	
	@Column(name = "seriesid", nullable = false)
	public long getSeriesid() {
		return this.seriesid;
	}
	
	public void setSeriesid(long seriesid) {
		this.seriesid = seriesid;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "phenomenontimestart", nullable = false, length = 29)
	public Date getPhenomenontimestart() {
		return this.phenomenontimestart;
	}
	
	public void setPhenomenontimestart(Date phenomenontimestart) {
		this.phenomenontimestart = phenomenontimestart;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "phenomenontimeend", nullable = false, length = 29)
	public Date getPhenomenontimeend() {
		return this.phenomenontimeend;
	}
	
	public void setPhenomenontimeend(Date phenomenontimeend) {
		this.phenomenontimeend = phenomenontimeend;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "resulttime", nullable = false, length = 29)
	public Date getResulttime() {
		return this.resulttime;
	}
	
	public void setResulttime(Date resulttime) {
		this.resulttime = resulttime;
	}
	
	@Column(name = "identifier", unique = true)
	public String getIdentifier() {
		return this.identifier;
	}
	
	public void setIdentifier(String identifier) {
		this.identifier = identifier;
	}
	
	@Column(name = "codespaceid")
	public Long getCodespaceid() {
		return this.codespaceid;
	}
	
	public void setCodespaceid(Long codespaceid) {
		this.codespaceid = codespaceid;
	}
	
	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}
	
	public void setDescription(String description) {
		this.description = description;
	}
	
	@Column(name = "deleted", nullable = false, length = 1)
	public char getDeleted() {
		return this.deleted;
	}
	
	public void setDeleted(char deleted) {
		this.deleted = deleted;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "validtimestart", length = 29)
	public Date getValidtimestart() {
		return this.validtimestart;
	}
	
	public void setValidtimestart(Date validtimestart) {
		this.validtimestart = validtimestart;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "validtimeend", length = 29)
	public Date getValidtimeend() {
		return this.validtimeend;
	}
	
	public void setValidtimeend(Date validtimeend) {
		this.validtimeend = validtimeend;
	}
	
	@Column(name = "unitid")
	public Long getUnitid() {
		return this.unitid;
	}
	
	public void setUnitid(Long unitid) {
		this.unitid = unitid;
	}
	
	@Column(name = "samplinggeometry")
	public Serializable getSamplinggeometry() {
		return this.samplinggeometry;
	}
	
	public void setSamplinggeometry(Serializable samplinggeometry) {
		this.samplinggeometry = samplinggeometry;
	}
	
}
