package it.sinergis.sunshine.suggestion.sospojo;

// Generated 9-lug-2015 8.41.16 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TaskStatus generated by hbm2java
 */
@Entity
@Table(name = "task_status", schema = "schedulingreport")
public class TaskStatus implements java.io.Serializable {
	
	private long id;
	private Long idProcess;
	private Date startProcess;
	private String status;
	private Date endProcess;
	private String description;
	private Date lastUpdate;
	
	public TaskStatus() {
	}
	
	public TaskStatus(long id) {
		this.id = id;
	}
	
	public TaskStatus(long id, Long idProcess, Date startProcess, String status, Date endProcess, String description,
			Date lastUpdate) {
		this.id = id;
		this.idProcess = idProcess;
		this.startProcess = startProcess;
		this.status = status;
		this.endProcess = endProcess;
		this.description = description;
		this.lastUpdate = lastUpdate;
	}
	
	@Id
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}
	
	public void setId(long id) {
		this.id = id;
	}
	
	@Column(name = "id_process")
	public Long getIdProcess() {
		return this.idProcess;
	}
	
	public void setIdProcess(Long idProcess) {
		this.idProcess = idProcess;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "start_process", length = 29)
	public Date getStartProcess() {
		return this.startProcess;
	}
	
	public void setStartProcess(Date startProcess) {
		this.startProcess = startProcess;
	}
	
	@Column(name = "status")
	public String getStatus() {
		return this.status;
	}
	
	public void setStatus(String status) {
		this.status = status;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "end_process", length = 29)
	public Date getEndProcess() {
		return this.endProcess;
	}
	
	public void setEndProcess(Date endProcess) {
		this.endProcess = endProcess;
	}
	
	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}
	
	public void setDescription(String description) {
		this.description = description;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_update", length = 29)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}
	
	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}
	
}
